### ISSUE TITLE
How do you serve the staticly built React app?

### ISSUE THREAD

**Issue by lexicalunit** [testdrivenio/fastapi-react#3]
Once you are ready to move to production, you'll need to have the backend and frontend running on the same domain (to take advantage of things like HTTP-Only cookies, for example).

You can build the static React app files like so:

```shell
cd frontend
npm run build
```

But now how do you actually serve these from your FastAPI backend?

In my application I tried doing something like this:

```python
api = FastAPI(root_path="/api")

# Create all my backend routes using @api.get() and @api/post() ...

app = FastAPI()
app.mount("/api", api)
app.mount("/", StaticFiles(directory="frontend/build", html=True), name="static")
```

This sort of works. I am able to get to my root frontend index by going to `http://localhost:5000`, but when I try to navigate to any other route in my React app (as defined by [`react-router-dom`](https://reactrouter.com/)) I just get a 404 Not Found from the backend.

Any ideas?

**Comment by mjhea0** [comment]
I'm not sure offhand how to do this in FastAPI, but you need to change `/` to some sort of catch all handler since you want to serve up the static build on anything that doesn't match `/api`.

Flask example: 

```python
@app .route("/", defaults={"path": ""})
@app.route("/<string:path>")
@app.route("/<path:path>")
def index(path):
    return render_template("index.html")
```
